name: file_foto
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  image_picker: ^0.6.0

  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icono2.1.png"

flutter:
  uses-material-design: true